hciattach_rtk: Fix missing mode argument to open()
In function 'open',
   inlined from 'rtk_write_btmac2file' at tools/hciattach_rtk.c:1706:5,
   inlined from 'rtk_get_bt_config.constprop' at tools/hciattach_rtk.c:1756:4:
/usr/include/bits/fcntl2.h:50:4: error: call to '__open_missing_mode' declared with attribute error: open with O_CREAT in second argument needs 3 arguments
    __open_missing_mode ();
    ^